//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waAutorClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Autor", Namespace="http://schemas.datacontract.org/2004/07/WcfEditorial")]
    [System.SerializableAttribute()]
    public partial class Autor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                if ((object.ReferenceEquals(this.paisField, value) != true)) {
                    this.paisField = value;
                    this.RaisePropertyChanged("pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutorO", Namespace="http://schemas.datacontract.org/2004/07/WcfEditorial")]
    [System.SerializableAttribute()]
    public partial class AutorO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int paisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pais {
            get {
                return this.paisField;
            }
            set {
                if ((this.paisField.Equals(value) != true)) {
                    this.paisField = value;
                    this.RaisePropertyChanged("pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pais", Namespace="http://schemas.datacontract.org/2004/07/WcfEditorial")]
    [System.SerializableAttribute()]
    public partial class Pais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceAutor")]
    public interface IServiceAutor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/listadoAutores", ReplyAction="http://tempuri.org/IServiceAutor/listadoAutoresResponse")]
        waAutorClient.ServiceReference1.Autor[] listadoAutores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/listadoAutores", ReplyAction="http://tempuri.org/IServiceAutor/listadoAutoresResponse")]
        System.Threading.Tasks.Task<waAutorClient.ServiceReference1.Autor[]> listadoAutoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/listadoAutoresO", ReplyAction="http://tempuri.org/IServiceAutor/listadoAutoresOResponse")]
        waAutorClient.ServiceReference1.AutorO[] listadoAutoresO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/listadoAutoresO", ReplyAction="http://tempuri.org/IServiceAutor/listadoAutoresOResponse")]
        System.Threading.Tasks.Task<waAutorClient.ServiceReference1.AutorO[]> listadoAutoresOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/listadoPais", ReplyAction="http://tempuri.org/IServiceAutor/listadoPaisResponse")]
        waAutorClient.ServiceReference1.Pais[] listadoPais();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/listadoPais", ReplyAction="http://tempuri.org/IServiceAutor/listadoPaisResponse")]
        System.Threading.Tasks.Task<waAutorClient.ServiceReference1.Pais[]> listadoPaisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/nuevoAutor", ReplyAction="http://tempuri.org/IServiceAutor/nuevoAutorResponse")]
        string nuevoAutor(waAutorClient.ServiceReference1.AutorO objA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/nuevoAutor", ReplyAction="http://tempuri.org/IServiceAutor/nuevoAutorResponse")]
        System.Threading.Tasks.Task<string> nuevoAutorAsync(waAutorClient.ServiceReference1.AutorO objA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/actualizaAutor", ReplyAction="http://tempuri.org/IServiceAutor/actualizaAutorResponse")]
        string actualizaAutor(waAutorClient.ServiceReference1.AutorO objA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/actualizaAutor", ReplyAction="http://tempuri.org/IServiceAutor/actualizaAutorResponse")]
        System.Threading.Tasks.Task<string> actualizaAutorAsync(waAutorClient.ServiceReference1.AutorO objA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/eliminaAutor", ReplyAction="http://tempuri.org/IServiceAutor/eliminaAutorResponse")]
        void eliminaAutor(waAutorClient.ServiceReference1.AutorO objA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAutor/eliminaAutor", ReplyAction="http://tempuri.org/IServiceAutor/eliminaAutorResponse")]
        System.Threading.Tasks.Task eliminaAutorAsync(waAutorClient.ServiceReference1.AutorO objA);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAutorChannel : waAutorClient.ServiceReference1.IServiceAutor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAutorClient : System.ServiceModel.ClientBase<waAutorClient.ServiceReference1.IServiceAutor>, waAutorClient.ServiceReference1.IServiceAutor {
        
        public ServiceAutorClient() {
        }
        
        public ServiceAutorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAutorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAutorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAutorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public waAutorClient.ServiceReference1.Autor[] listadoAutores() {
            return base.Channel.listadoAutores();
        }
        
        public System.Threading.Tasks.Task<waAutorClient.ServiceReference1.Autor[]> listadoAutoresAsync() {
            return base.Channel.listadoAutoresAsync();
        }
        
        public waAutorClient.ServiceReference1.AutorO[] listadoAutoresO() {
            return base.Channel.listadoAutoresO();
        }
        
        public System.Threading.Tasks.Task<waAutorClient.ServiceReference1.AutorO[]> listadoAutoresOAsync() {
            return base.Channel.listadoAutoresOAsync();
        }
        
        public waAutorClient.ServiceReference1.Pais[] listadoPais() {
            return base.Channel.listadoPais();
        }
        
        public System.Threading.Tasks.Task<waAutorClient.ServiceReference1.Pais[]> listadoPaisAsync() {
            return base.Channel.listadoPaisAsync();
        }
        
        public string nuevoAutor(waAutorClient.ServiceReference1.AutorO objA) {
            return base.Channel.nuevoAutor(objA);
        }
        
        public System.Threading.Tasks.Task<string> nuevoAutorAsync(waAutorClient.ServiceReference1.AutorO objA) {
            return base.Channel.nuevoAutorAsync(objA);
        }
        
        public string actualizaAutor(waAutorClient.ServiceReference1.AutorO objA) {
            return base.Channel.actualizaAutor(objA);
        }
        
        public System.Threading.Tasks.Task<string> actualizaAutorAsync(waAutorClient.ServiceReference1.AutorO objA) {
            return base.Channel.actualizaAutorAsync(objA);
        }
        
        public void eliminaAutor(waAutorClient.ServiceReference1.AutorO objA) {
            base.Channel.eliminaAutor(objA);
        }
        
        public System.Threading.Tasks.Task eliminaAutorAsync(waAutorClient.ServiceReference1.AutorO objA) {
            return base.Channel.eliminaAutorAsync(objA);
        }
    }
}
